const express=require("express"),cors=require("cors"),multer=require("multer"),fs=require("fs"),path=require("path"),http=require("http"),crypto=require("crypto"),jwt=require("jsonwebtoken"),{WebSocketServer}=require("ws");
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server});
const PORT=process.env.PORT||3000,ADMIN_USER=process.env.ADMIN_USER||"admin",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"change-me",JWT_SECRET=process.env.JWT_SECRET||crypto.randomBytes(32).toString("hex");
const DATA=path.join(__dirname,"data"),UPLOADS=path.join(__dirname,"uploads"),DB=path.join(DATA,"db.json");
fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(UPLOADS,{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,'{"devices":[],"messages":[],"files":[]}');
app.use(cors());app.use(express.json({limit:"1mb"}));app.use("/uploads",express.static(UPLOADS));
const read=()=>JSON.parse(fs.readFileSync(DB,"utf8")),write=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2)),uid=p=>p+"_"+crypto.randomUUID(),code=()=>String(Math.floor(100000+Math.random()*900000));
function auth(req,res,next){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"Unauthorized"});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:"Invalid token"})}}
app.get("/api/health",(q,s)=>s.json({ok:true,version:"4.0.0"}));
app.post("/api/auth/login",(q,s)=>{const{username,password}=q.body||{};if(username!==ADMIN_USER||password!==ADMIN_PASSWORD)return s.status(401).json({error:"Sai tài khoản hoặc mật khẩu"});s.json({token:jwt.sign({role:"admin",username},JWT_SECRET,{expiresIn:"12h"})})});
app.post("/api/devices/register",(q,s)=>{const{deviceId,name,model}=q.body||{},d=read();let x=d.devices.find(v=>v.deviceId===deviceId);if(!x){x={deviceId:deviceId||uid("device"),name:name||"Android",model:model||"",pairingCode:code(),createdAt:new Date().toISOString(),lastSeenAt:new Date().toISOString()};d.devices.push(x)}else{x.name=name||x.name;x.model=model||x.model;x.lastSeenAt=new Date().toISOString()}write(d);s.json(x)});
app.post("/api/devices/pair",(q,s)=>{const{deviceId,pairingCode}=q.body||{},x=read().devices.find(v=>v.deviceId===deviceId&&v.pairingCode===pairingCode);if(!x)return s.status(401).json({error:"Mã ghép nối không đúng"});s.json({ok:true,deviceId:x.deviceId,name:x.name})});
app.get("/api/devices",auth,(q,s)=>s.json(read().devices));app.get("/api/messages/:id",auth,(q,s)=>s.json(read().messages.filter(x=>x.deviceId===q.params.id)));app.get("/api/devices/:id/files",auth,(q,s)=>s.json(read().files.filter(x=>x.deviceId===q.params.id)));
const storage=multer.diskStorage({destination:UPLOADS,filename:(q,f,cb)=>cb(null,Date.now()+"_"+crypto.randomUUID()+"_"+path.basename(f.originalname).replace(/[^\w.\-\sÀ-ỹ]/g,"_"))}),upload=multer({storage});
app.post("/api/upload",upload.single("file"),(q,s)=>{if(!q.file)return s.status(400).json({error:"No file"});if(!q.body.deviceId){fs.unlinkSync(q.file.path);return s.status(400).json({error:"Missing deviceId"})}const d=read(),f={id:uid("file"),deviceId:q.body.deviceId,originalName:q.file.originalname,mimeType:q.file.mimetype,size:q.file.size,storedName:q.file.filename,url:"/uploads/"+encodeURIComponent(q.file.filename),createdAt:new Date().toISOString()};d.files.push(f);write(d);s.json(f)});
const sendDevice=(id,p)=>{let ok=false;for(const c of wss.clients)if(c.readyState===1&&c.deviceId===id){c.send(JSON.stringify(p));ok=true}return ok};
wss.on("connection",ws=>ws.on("message",raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==="auth"){if(m.role==="admin"){try{const p=jwt.verify(m.token,JWT_SECRET);if(p.role!=="admin")throw 0;ws.role="admin";ws.auth=true;ws.send(JSON.stringify({type:"auth_ok"}))}catch{ws.close(1008,"auth")}}else if(m.role==="device"){const x=read().devices.find(v=>v.deviceId===m.deviceId&&v.pairingCode===m.pairingCode);if(!x){ws.close(1008,"pairing");return}ws.role="device";ws.auth=true;ws.deviceId=m.deviceId;ws.send(JSON.stringify({type:"auth_ok",deviceId:m.deviceId}))}return}
if(!ws.auth||m.type!=="chat"||!m.deviceId||!m.text)return;const msg={id:uid("msg"),deviceId:m.deviceId,sender:m.sender||"unknown",text:String(m.text).slice(0,5000),createdAt:new Date().toISOString()},d=read();d.messages.push(msg);write(d);sendDevice(m.deviceId,msg);for(const c of wss.clients)if(c.readyState===1&&c.role==="admin")c.send(JSON.stringify(msg))}));
server.listen(PORT,()=>console.log("Chat Device V4 listening on "+PORT));